import type { Document, Template } from "./types"

export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "Facturas Diciembre 2024",
    description: "Procesamiento de facturas del último mes del año",
    user_id: "mock-user-1",
    fields: [
      {
        id: "f1",
        field_name: "numero_factura",
        type: "text",
        description: "Número de factura",
        formats: ["FAC-", "INV-"],
        required: true,
        order: 0,
      },
      {
        id: "f2",
        field_name: "fecha",
        type: "date",
        description: "Fecha de emisión",
        formats: [],
        required: true,
        order: 1,
      },
      {
        id: "f3",
        field_name: "monto",
        type: "number",
        description: "Monto total",
        formats: ["$", "€"],
        required: true,
        order: 2,
      },
      {
        id: "f4",
        field_name: "cliente",
        type: "text",
        description: "Nombre del cliente",
        formats: [],
        required: true,
        order: 3,
      },
    ],
    rows: [
      {
        id: "r1",
        document_id: "1",
        data: {
          numero_factura: "FAC-2024-001",
          fecha: "2024-12-01",
          monto: 1250.5,
          cliente: "Empresa ABC S.A.",
        },
        file_metadata: {
          filename: "factura_001.pdf",
          file_size: 245760,
          file_type: "application/pdf",
          upload_date: "2024-12-01T10:30:00Z",
        },
        created_at: "2024-12-01T10:30:00Z",
      },
      {
        id: "r2",
        document_id: "1",
        data: {
          numero_factura: "FAC-2024-002",
          fecha: "2024-12-03",
          monto: 890.25,
          cliente: "Corporación XYZ",
        },
        file_metadata: {
          filename: "factura_002.pdf",
          file_size: 198432,
          file_type: "application/pdf",
          upload_date: "2024-12-03T14:15:00Z",
        },
        created_at: "2024-12-03T14:15:00Z",
      },
    ],
    created_at: "2024-11-15T09:00:00Z",
    updated_at: "2024-12-03T14:15:00Z",
  },
  {
    id: "2",
    name: "Contratos de Clientes",
    description: "Base de datos de información contractual",
    user_id: "mock-user-1",
    fields: [
      {
        id: "f5",
        field_name: "numero_contrato",
        type: "text",
        description: "Número de contrato",
        formats: ["CONT-"],
        required: true,
        order: 0,
      },
      {
        id: "f6",
        field_name: "cliente",
        type: "text",
        description: "Nombre del cliente",
        formats: [],
        required: true,
        order: 1,
      },
      {
        id: "f7",
        field_name: "fecha_inicio",
        type: "date",
        description: "Fecha de inicio del contrato",
        formats: [],
        required: true,
        order: 2,
      },
      {
        id: "f8",
        field_name: "valor_mensual",
        type: "number",
        description: "Valor mensual del contrato",
        formats: ["$"],
        required: true,
        order: 3,
      },
    ],
    rows: [
      {
        id: "r3",
        document_id: "2",
        data: {
          numero_contrato: "CONT-2024-001",
          cliente: "TechCorp Solutions",
          fecha_inicio: "2024-01-15",
          valor_mensual: 5000,
        },
        created_at: "2024-01-15T08:00:00Z",
      },
    ],
    created_at: "2024-01-10T09:00:00Z",
    updated_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "3",
    name: "Inventario de Productos",
    description: "Control de stock y productos",
    user_id: "mock-user-1",
    fields: [
      {
        id: "f9",
        field_name: "codigo_producto",
        type: "text",
        description: "Código del producto",
        formats: ["PROD-"],
        required: true,
        order: 0,
      },
      {
        id: "f10",
        field_name: "nombre",
        type: "text",
        description: "Nombre del producto",
        formats: [],
        required: true,
        order: 1,
      },
      {
        id: "f11",
        field_name: "cantidad",
        type: "number",
        description: "Cantidad en stock",
        formats: [],
        required: true,
        order: 2,
      },
      {
        id: "f12",
        field_name: "precio",
        type: "number",
        description: "Precio unitario",
        formats: ["$"],
        required: true,
        order: 3,
      },
    ],
    rows: [],
    created_at: "2024-11-20T10:00:00Z",
    updated_at: "2024-11-20T10:00:00Z",
  },
]

export const mockTemplates: Template[] = [
  {
    id: "t1",
    name: "Plantilla de Facturas",
    description: "Estructura estándar para procesamiento de facturas",
    user_id: "mock-user-1",
    fields: [
      {
        id: "tf1",
        field_name: "numero_factura",
        type: "text",
        description: "Número de factura",
        formats: ["FAC-", "INV-"],
        required: true,
        order: 0,
      },
      {
        id: "tf2",
        field_name: "fecha",
        type: "date",
        description: "Fecha de emisión",
        formats: [],
        required: true,
        order: 1,
      },
      {
        id: "tf3",
        field_name: "monto",
        type: "number",
        description: "Monto total",
        formats: ["$", "€"],
        required: true,
        order: 2,
      },
      {
        id: "tf4",
        field_name: "cliente",
        type: "text",
        description: "Nombre del cliente",
        formats: [],
        required: true,
        order: 3,
      },
    ],
    created_at: "2024-10-01T09:00:00Z",
  },
  {
    id: "t2",
    name: "Plantilla de Contratos",
    description: "Estructura para documentos contractuales",
    user_id: "mock-user-1",
    fields: [
      {
        id: "tf5",
        field_name: "numero_contrato",
        type: "text",
        description: "Número de contrato",
        formats: ["CONT-"],
        required: true,
        order: 0,
      },
      {
        id: "tf6",
        field_name: "cliente",
        type: "text",
        description: "Nombre del cliente",
        formats: [],
        required: true,
        order: 1,
      },
      {
        id: "tf7",
        field_name: "fecha_inicio",
        type: "date",
        description: "Fecha de inicio",
        formats: [],
        required: true,
        order: 2,
      },
    ],
    created_at: "2024-09-15T09:00:00Z",
  },
]
